# Generated by Django 5.1.4 on 2024-12-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='type',
            field=models.CharField(choices=[('spotify', 'Spotify')], max_length=50),
        ),
    ]
