# Generated by Django 5.1.4 on 2024-12-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_externallink_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externallink',
            old_name='type',
            new_name='spotify',
        ),
        migrations.AddField(
            model_name='externallink',
            name='youtube',
            field=models.CharField(choices=[('youtube', 'YouTube')], default='Youtube', max_length=50),
            preserve_default=False,
        ),
    ]
