# Generated by Django 5.1.4 on 2024-12-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_rename_type_externallink_spotify_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallink',
            name='url',
        ),
        migrations.AlterField(
            model_name='externallink',
            name='spotify',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='youtube',
            field=models.URLField(),
        ),
    ]
