# Generated by Django 5.1.4 on 2024-12-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_pdfdocument_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
