# Generated by Django 5.1.4 on 2024-12-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_pdfdocument_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='cover_image',
            field=models.ImageField(default='null', upload_to='cover_image'),
            preserve_default=False,
        ),
    ]
