# Generated by Django 5.1.4 on 2024-12-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_pdfdocument_cover_image_delete_coverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='spotify',
            field=models.URLField(default='sp.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='youtube',
            field=models.URLField(default='yt.com'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExternalLink',
        ),
    ]
